#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER" /var/www/
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
