#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER" /var/www/
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "25i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permannet;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
sudo service nginx reload
