#!/usr/bin/env bash
# Bash script that configures an Ubuntu server 
cp /etc/hosts ~/hosts.new
sed -i "s/localhost/127.0.0.2/g" ~/hosts.new
sed -i "s/facebook.com/8.8.8.8/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
